### ISSUE TITLE
hello,关于动画想请教一下

### ISSUE THREAD

**Issue by tysheng** [dreamcontinue/Lavender#1]
很想实现你的项目中点击图片放大，关闭后然后缩小的动画，自己试了几次没有实现，请问应该分成几步呢？或者有相关文章资料可以分享一下

**Comment by syt2** [comment]
我是参考这篇文章的 http://blog.csdn.net/mr_wrong1/article/details/49669275
可以在GitHub上搜索meizi找到该作者

**Comment by tysheng** [comment]
@dreamcontinue thx
